# Generated by Django 2.2 on 2020-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200715_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerrelation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
